lib/index.ts, lib/plugins/metricsPlugin.ts, lib/plugins/publicHealthcheckPlugin.spec.ts, lib/plugins/publicHealthcheckPlugin.ts
Lightweight healthcheck for public access
=> Implement public healthcheck plugin

lib/index.ts, lib/plugins/publicHealthcheckPlugin.spec.ts, lib/plugins/publicHealthcheckPlugin.ts, package.json
Make it possible to define your own response
=> Add support for customizing healthcheck response

CONTRIBUTING.md, lib/plugins/newrelicTransactionManagerPlugin.ts
I'm not sure this will capture async context from the parent app correctly, needs testing
=> Expose method for custom newrelic attributes

lib/plugins/publicHealthcheckPlugin.ts
Make app instance available inside healthchecks (e. g. for DI purposes)
=> Pass app to healthchecks

README.md, lib/plugins/newrelicTransactionManagerPlugin.ts
- Populated README with plugin documentation
- Fixed typo in `addCustomAttribute` method name for NewRelic Transaction Manager Plugin (hence the new version)
=> AUT-103 Populate README

lib/plugins/healthcheckMetricsPlugin.spec.ts, lib/plugins/healthcheckMetricsPlugin.ts
=> Fix prom healthcheck return type

lib/index.ts, lib/plugins/publicHealthcheckPlugin.spec.ts, lib/plugins/publicHealthcheckPlugin.ts
Align with https://github.com/lokalise/platform-handbook/blob/main/processes/health-check-requirements.md
=> [AP-372] Modify public healthcheck to use /health endpoint by default and support optional checks

lib/plugins/healthcheckMetricsPlugin.spec.ts, lib/plugins/publicHealthcheckPlugin.spec.ts, lib/plugins/publicHealthcheckPlugin.ts
Include list of specific checks in healthcheck response
=> Include healthchecks in response

lib/index.ts
=> Add missing export

.github/dependabot.yml, package.json
Try to fix prisma incompatibility with otel
=> Bump and lock opentelemetry

README.md, lib/index.ts, lib/plugins/unhandledExceptionPlugin.ts, package.json
The PR adds Unhandled Exception plugin
=> feat: Add unhandledExceptionPlugin

lib/plugins/requestContextProviderPlugin.ts
Automatically include requestId in request logs
=> Automatically log request id

.eslintrc.json, lib/errors/errorHandler.spec.ts, lib/errors/errorHandler.ts, lib/index.ts, package.json
Extract common part of global error handler
=> Implement reusable error handler

lib/index.ts, lib/plugins/bugsnagPlugin.ts
=> Expose ErrorReporter wrapper for Bugsnag

README.md, lib/errors/publicErrors.ts, lib/index.ts, lib/jwt-utils/tokenUtils.spec.ts, lib/jwt-utils/tokenUtils.ts, package.json, tsconfig.json, vitest.config.ts
=> AP-2305 add token utils

lib/index.ts, lib/plugins/bugsnagPlugin.ts, package.json
=> AP-3190 Reexport of addFeatureFlag.

lib/plugins/newrelicTransactionManagerPlugin.ts, package.json
=> Use node-core TransactionObservabilityManager interface

package.json
=> Switch to pino 9 to unblock updates

package.json
Updating error utils to use the latest improvements on Bugsnag report
=> Error utils 1.2.0

package.json
=> Forcing error-utils 1.2.2

lib/plugins/amplitude/AmplitudeAdapter.spec.ts, lib/plugins/amplitude/AmplitudeAdapter.ts
=> Support user_id "SYSTEM"

lib/errors/errorHandler.ts
Previously we were losing x-request-id
=> Fix error logging

lib/errors/errorHandler.spec.ts, lib/errors/errorHandler.ts
Enhanced error reporting to include any throwable
=> Enhanced error reporting to include generic and other error types

lib/plugins/bull-mq-metrics/MetricsCollector.ts, lib/plugins/bull-mq-metrics/ObservableQueue.ts, lib/plugins/bullMqMetricsPlugin.spec.ts, package.json
- added metrics for duration of failed jobs
- grouped job statuses within a single Gauge by "status" labelName
=> adjust bull mq metrics

lib/index.ts
=> missing export

package.json
Support wider range of dependencies
=> Support a range of background-jobs lib

lib/index.ts
Adding `commonHealthcheckPlugin` to exports
=> MET-425 Fix: Export commonHealthCheckPlugin

README.md, lib/index.ts, lib/plugins/stripTrailingSlashPlugin.spec.ts, lib/plugins/stripTrailingSlashPlugin.ts
This PR adds stripTrailingSlashPlugin. The use-case is described in the README.md
=> feat: add stripTrailingSlashPlugin

lib/plugins/newrelicTransactionManagerPlugin.ts
=> Fixing new relic require

lib/plugins/newrelicTransactionManagerPlugin.ts
=> Moving new relic to local instance

lib/plugins/newrelicTransactionManagerPlugin.ts
=> Using newrelic default

lib/plugins/newrelicTransactionManagerPlugin.ts
These are the methods used by CF Connector. If we want to switch CF Connector to use newrelic transaction manager plugin, we need to provide these.
=> feat: Expose NR user & controller methods

lib/plugins/newrelicTransactionManagerPlugin.ts, package.json
Useful for synchronous constructors
=> Support synchronous creation of noop newrelic manager
