package.json

`esquery` package is a transitive dependency for us - and a broken version was released last night.
This PR fixes esquery to 1.4.0
See: https://github.com/estools/esquery/issues/135

Install fixed version of esquery

---

lib/plugins/publicHealthcheckPlugin.spec.ts
lib/plugins/publicHealthcheckPlugin.ts

This allows using same healthchecks in contexts that expect to throw an error and also a non-throwing handling

Wrap healthcheck into Either

---

lib/plugins/publicHealthcheckPlugin.spec.ts
lib/plugins/publicHealthcheckPlugin.ts

When service is unhealthy, healthcheck should be returning 500 so that it is restarted

When healthcheck fails, it should be 500

---

package.json

(see https://github.com/angular/angular-cli/issues/13886#issuecomment-471927518)
This fixes library users breaking when they don't have tslib

Include tslib

---

README.md
lib/index.ts
lib/plugins/amplitudePlugin.spec.ts
lib/plugins/amplitudePlugin.ts

Refactoring amplitudePlugin to decorate fastify with an instance of the new Class Amplitude and being able to inject it across the app via DI.
It comes before we were not happy with storing the global config into the plugin

Fastify amplitude decorator

---

lib/plugins/metricsPlugin.ts
lib/plugins/requestContextProviderPlugin.ts
package.json

Update to the next newrelic semver major and some other dependencies

---

.github/workflows/release.yml

Seems like our release flow was broken in v4

Try to fix releases

---

lib/errors/errorHandler.ts

`instanceof` breaks when check is done across multiple package boundaries (e. g. fastify-exports imports their own Zod, and consuming application imports their own), so we are going to rely on a name instead.

Fix instanceof check across libraries

---

lib/errors/errorHandler.ts
lib/index.ts
lib/plugins/healthcheck/publicHealthcheckPlugin.spec.ts
lib/plugins/healthcheck/publicHealthcheckPlugin.ts

This allows exposing dynamically resolved data via healthcheck

Support custom infoProviders on healthcheck

---

package.json

Error utils 1.2.0 has an error on build which make it to not work. With this PR we are forcing forcing fastify-extras to use the fixed version

Forcing error-utils 1.2.1

---

lib/plugins/healthcheck/healthcheckMetricsPlugin.spec.ts
lib/plugins/metricsPlugin.spec.ts
package.json

node-core will be dropping http-client in the next semver major, so we should start switching everywhere

Use backend-http-client

---

tsconfig.json

After #173 has been merged, TS build generates incorrect output structure, incompatible with the package.json:
Before:
```
- dist/index.d.ts
```
After:
```
- dist/lib/index.d.ts
```
Issue happened due to spec files participating in a build which started to require new files from the the root `test` folder - adding it to the outputs. This PR fixes that.

Fix incorrect TS build

---

README.md
lib/index.ts
lib/route-utils/authPreHandlers.spec.ts
lib/route-utils/authPreHandlers.ts
package.json

Adding pre handler to checking if statically configured token is valid for request. Configured on route level.

AP-4667 PreHandler for static tokens.

---

README.md
lib/plugins/bull-mq-metrics/MetricsCollector.ts
lib/plugins/bull-mq-metrics/queueDiscoverers.ts
lib/plugins/bullMqMetricsPlugin.spec.ts
lib/plugins/bullMqMetricsPlugin.ts
package.json

To use bullmq metrics plugin in Flow, we need to support multiple redis instances in configuration. Since `redisClients` are accepted as array now, it's a breaking change

AP-4397 support for multiple redis clients in BullMQ metrics

---

README.md
lib/plugins/bull-mq-metrics/MetricsCollector.ts
lib/plugins/bull-mq-metrics/ObservableQueue.ts
lib/plugins/bull-mq-metrics/queueDiscoverers.ts
lib/plugins/bullMqMetricsPlugin.spec.ts
lib/plugins/bullMqMetricsPlugin.ts
package.json
test/mocks/TestDepedendencies.ts

Context: https://lokalise.atlassian.net/browse/AP-5015
Updates `bullMqMetricsPlugin` to operate on RedisConfigs instead of Redis instances, so that the default parameters are injected before creating an instance

AP-5015 update bullmq metrics plugin to use redis configs instead of redis instances

---

lib/errors/errorHandler.spec.ts
lib/errors/errorHandler.ts
lib/plugins/amplitude/AmplitudeAdapter.spec.ts
lib/plugins/amplitude/amplitudePlugin.spec.ts
lib/plugins/bullMqMetricsPlugin.spec.ts
test/mocks/TestBackgroundJobProcessor.ts
test/mocks/TestDependencies.ts
test/setup.ts
vitest.config.mts

call to errorReporter now include request params

Add extra context for error reporter

---

lib/errors/errorHandler.spec.ts
lib/errors/errorHandler.ts
package.json

New behaviour is actually more correct, because previously it was not possible to differentiate between request validation errors and internal validation errors (e. g. while validating a DB entity). Now they have different error types.

Update error handler to accomodate for changes in fastify-type-provider-zod

---

lib/plugins/bullMqMetricsPlugin.spec.ts
lib/plugins/healthcheck/healthcheckMetricsPlugin.spec.ts
lib/plugins/metricsPlugin.spec.ts
lib/plugins/metricsPlugin.ts
lib/plugins/prometheus/PrometheusCounterTransactionManager.spec.ts

fastify expects preconfigured logger to be passed as loggerInstance instead of a logger.

Use more fastify5-friendly logger definition

---

lib/errors/errorHandler.ts
lib/index.ts
lib/plugins/healthcheck/healthcheckCommons.ts
lib/plugins/healthcheck/healthcheckMetricsPlugin.ts
lib/plugins/healthcheck/publicHealthcheckPlugin.ts
lib/plugins/pluginsCommon.ts

CommonLogger that we rely upon and FastifyBaseLogger are different, this is causing clashes

Adjust FastifyInstance types

---

lib/plugins/amplitude/amplitudePlugin.ts
lib/plugins/bugsnagPlugin.ts
lib/plugins/bullMqMetricsPlugin.ts
lib/plugins/healthcheck/healthcheckMetricsPlugin.ts
lib/plugins/healthcheck/publicHealthcheckPlugin.ts
lib/plugins/metricsPlugin.ts
lib/plugins/newrelicTransactionManagerPlugin.ts
lib/plugins/requestContextProviderPlugin.ts
lib/plugins/splitIOFeatureManagerPlugin.ts
lib/plugins/unhandledExceptionPlugin.ts

Fastify 5 is more picky with regards to what plugins can be awaited and which cannot be, so let's make that contract explicit and adjust asynchronous plugins to rely on promises.

Explicit plugin types

---

package.json

Semver major, because older bullmq is no longer supported

Update to a newer BullMQ

---

lib/plugins/amplitude/AmplitudeAdapter.spec.ts
lib/plugins/amplitude/AmplitudeAdapter.ts

Accept optional `groups` in Amplitude track calls as `Record<string, any>` (matching the Amplitude API spec: https://amplitude.github.io/Amplitude-TypeScript/interfaces/_amplitude_analytics_node.Types.BaseEvent.html#groups)

AP-5780 Accept groups in Amplitude track calls

---

README.md
lib/plugins/healthcheck/commonHealthcheckPlugin.spec.ts
lib/plugins/healthcheck/commonHealthcheckPlugin.ts

This PR adds a new `commonHealthcheckPlugin`, which is registering two routes:
* A public one `GET /`
* A private one `GET /health`
Public route contain only resulting heartbeat from all provided healthchecks in a response. Extra info is also omitted.
Private route contain exactly the same response as `publicHealthcheckPlugin` has.

MET-425 Create a common healthcheck plugin for public and private endpoints

---

lib/plugins/healthcheck/commonHealthcheckPlugin.spec.ts
lib/plugins/healthcheck/commonHealthcheckPlugin.ts

This PR adds an option to disable healthcheck on the root route. Additionally is simplifies a bunch of logic by using optional chaining, async/await instead of then, and simplifies typing for plugins by following info from https://www.npmjs.com/package/fastify-plugin

feat: add option to disable healthcheck on root route

---

lib/plugins/stripTrailingSlashPlugin.ts

This PR improves logic in stripTrailingSlashPlugin by hardcoding origin. The previous implementation didn't work in case of missing port.

chore: improve trailing slash plugin reliability

---

lib/plugins/amplitude/AmplitudeAdapter.spec.ts
lib/plugins/amplitude/AmplitudeAdapter.ts

User ids can have different formats, depending on the app/service, hence, the library should be flexible in this regard

Making aplitude user id flexible

---

lib/plugins/bull-mq-metrics/ObservableQueue.ts
package.json
tsconfig.json

This PR:
- Makes bull mq monitoring plugin to log all job statuses
- Removes unneeded tsconfig.json params (redis-semaphore is no longer an issue)
- Removes unneeded tslib package - it is not used after migration to @lokalise/tsconfig

feat: monitor all bull mq job statuses

---

lib/plugins/bull-mq-metrics/ObservableQueue.ts

This PR removes 'completed' and 'failed' from getJobCounts() because their counts are misleading due to the capped retention of completed jobs (currently limited to 50). This limit results in mostly constant counts that don’t reflect actual job processing volume. By excluding these statuses and relying on event-driven metrics updated on every job completion or failure, metrics become accurate and reflect real-time activity instead of capped historical data.

feat: remove collecting missleading bullmq metrics
